### ISSUE TITLE
Secret(k8s) cannot be used to define COSIGNPUBKEY

### ISSUE THREAD

**Issue by krych14m** [eumel8/cosignwebhook#17]
**Current behaviour:**
If I define Secret(k8s) and use it to define Pod(k8s) environment variable COSIGNPUBKEY (env[].valueFrom.secretKeyRef), Webhook does not take Secret(k8s) value.

**Expected behaviour:**
I am able to define COSIGNPUBKEY value using Secret(k8s).

**Comment by puffitos** [comment]
@eumel8 I'll take a look next week and try to implement this.

**Comment by puffitos** [comment]
Closed by #18
