### ISSUE TITLE
Only ECDSA keys are accepted - RSA keys should be accepted as well

### ISSUE THREAD

**Issue by CerRegulus** [eumel8/cosignwebhook#57]
## Describe the problem

A customer is struggling to use CosignWebhook after updating their Cosign key for their images. Event:
```
[FailedCreate] Internal error occurred: failed calling webhook "cosignwebhook.caas.telekom.de": failed to call webhook: Post "https://cosignwebhook.cosignwebhook.svc:443/validate?timeout=10s": EOF
```

They can't use ECDSA keys...

The use of RSA public keys is forbidden; only ECDSA keys are allowed.

cosign logs:
```
2024/08/13 11:10:11 http: panic serving 10.42.33.0:63420: interface conversion: crypto.PublicKey is *rsa.PublicKey, not *ecdsa.PublicKey
```

## Possible solution
- Allow RSA keys as well

If I understand the code correctly, the ECDSA requirement arises here:
https://github.com/eumel8/cosignwebhook/blob/92c9f45bf2b91488c5ff268f24a49e3e4816db77/webhook/cosignwebhook.go#L341
Therefore, this part would need to be adjusted to also accept other PublicKeys.

**Comment by eumel8** [comment]
would be an enhancement to use other types of keys. At least it needs a key check to prevent the panic.

**Comment by puffitos** [comment]
The feature is ready in the https://github.com/eumel8/cosignwebhook/tree/feat/rsa-keys branch. I'll refactor the tests, so we get a full E2E test suite for the RSA keypair as well, and then we can make a release.

I don't want to have almost 2 exact copies of the E2E tests, as this would seriously degrate the readability of the test cases, which are arguably already verbose and chunky :) The whole feature will come in 2 PRs, I think. I'll open the first one in the next couple of days @eumel8.
